from search import *
from tests.characters import *
from tests.chats import *
from tests.concepts import *
from tests.issues import *
from tests.locations import *
from tests.movies import *
from tests.objects import *
from tests.people import *
from tests.powers import *
